# Generated by Django 4.2.5 on 2023-10-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_blog_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blog_images',
            field=models.ImageField(default=None, upload_to='blog_images/'),
        ),
    ]
